server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "uat"
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: "@Q"
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: "guest"
#    password: "guest"
#acturator related config
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: "Cards"
    description: "Cards Microservice"
    version: "1.0.0"