spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lowerCaseServiceId: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: ""
  info:
    env:
      enabled: true
info:
  app:
    name: "gatewayserver"
    description: "gatewayserver for Microservice"
    version: "1.0.0"
logging:
  level:
    com:
      example:
        gatewayserver: DEBUG
