spring:
  application:
    name: "configserver"
  profiles:
#   active: native
      active: git
  cloud:
    config:
      server:
        #native:
#       search-locations: "classpath:/config"
         # search-locations: "file:/Users/sakshamvaishya/Downloads/Microservice Course/Config"
        git:
          uri: "https://github.com/saksham4768/Microservices-configuration.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
encrypt:
  key: qwe1234567890qwe@@Q
server:
  port: 8071