services:
  accountsdb:
    image: mysql
    container_name: accountsdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "accountsdb"
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    image: mysql
    container_name: cardsdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: "cardsdb"
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    image: mysql
    container_name: loansdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: "loansdb"
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "saksham2388/configserver:1.0"
    container_name: configserverContainer
    ports:
      - "8071:8071"
    #      - "8081:8081" Multiple port mapping
    healthcheck:
      test:  "curl --fail --silent http://localhost:8071/actuator/health/readincess | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      service: microservice-base-config
      file: common-config.yml

  accounts:
    image: "saksham2388/account:1.0"
    container_name: accountsContainer
    ports:
      - "8080:8080"
#      - "8081:8081" Multiple port mapping
    depends_on:
      accountsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATABASE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    extends:
      service: microservice-configserver-config
      file: common-config.yml

  loans:
    image: "saksham2388/loans:1.0"
    container_name: loansContainer
    ports:
      - "8090:8090"
    #      - "8081:8081" Multiple port mapping
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATABASE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      service: microservice-configserver-config
      file: common-config.yml

  cards:
    image: "saksham2388/cards:1.0"
    container_name: cardsContainer
    ports:
      - "9000:9000"
    #      - "8081:8081" Multiple port mapping
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATABASE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      service: microservice-configserver-config
      file: common-config.yml

networks:
  network1:
    driver: "bridge"
